### ISSUE TITLE
phone number reinterpreted wrongly

### ISSUE THREAD

**Issue by daedadu** [emacs-helm/helm-bbdb#14]
Assume we have a contact where I want to add a number that is as the following

`+49123456789` via `i` in the contact buffer. This then becomes, `(491) 234-5678 x9`
It looks like it is assuming a certain format of the number. But the german numbers don't match this format.

**Comment by jagrg** [comment]
Try setting `bbdb-phone-style` to nil and see if that works for you.

**Comment by daedadu** [comment]
Thx that helped
