### ISSUE TITLE
Add to melpa

### ISSUE THREAD

**Issue by jschaf** [emacs-helm/helm-bbdb#3]
Hi,

Would you mind adding this to MELPA?

**Comment by ghost** [comment]
It's on my list to do that (since quite a while I must admit), but the preparations are not yet done.  Feel free to ping me if you think I procrastinate, but I think it will happen soon.

**Comment by thierryvolpiatto** [comment]
If helm-bbdb is working now as fine as before (old bbdb) perhaps it is time to put it on MELPA ?

**Comment by thierryvolpiatto** [comment]
Here the process to make this done:
1) Fork melpa.
2) Create a branch on your local melpa repository.
3) Create a file "recipes/helm-bbdb" and add something like:
`(helm-bbdb :repo "emacs-helm/helm-bbdb" :fetcher github)`
4) Push to your fork on github and create a PR on melpa requesting insertion
of helm-bbdb in MELPA.

**Comment by ghost** [comment]
Thierry Volpiatto notifications@github.com writes:

> If helm-bbdb is working now as fine as before (old bbdb) perhaps it is
> time to put it on MELPA ?

Sure, I can do that (after merging the outstanding PR).

Thierry, I hope we can work a bit more respectful with each other than
in our last conversation.  If we can't, I think I'll stop working on
Helm stuff.

Thanks for the reminder,

Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen notifications@github.com writes:

> Sure, I can do that (after merging the outstanding PR).

Good, I didn't do that myself because I don't know the state of
helm-bbdb actually.

> Thierry, I hope we can work a bit more respectful with each other than
> in our last conversation.

We can, sorry if my rudeness hurts you at some time.

Thanks.

## 

Thierry

**Comment by thierryvolpiatto** [comment]
Ok, now helm-bbdb is on melpa.
