### ISSUE TITLE
filtering of bbdb records is slow

### ISSUE THREAD

**Issue by deusmax** [emacs-helm/helm-bbdb#7]
## Expected behavior
Helm filtering of bbdb records should be lightning fast !

## Actual behavior from emacs-helm.sh if possible
After the list of records is created, the filtering seems to "freeze" during input (typing).

Buffer "*helm bbdb*" is updated with the list of entries names very fast.
My bbdb database has only 50 records.

## Steps to reproduce (recipe)
Function executed: helm-bbdb

## Describe versions of helm, emacs, operating system etc.
GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.20.6, cairo version 1.14.6) of 2017-04-18
**bbdb:** 20170129.2224
**helm-bbdb:** 20161122.522
Platform: Debian Linux, testing (stretch)

**Comment by thierryvolpiatto** [comment]
deusmax <notifications@github.com> writes:

> Expected behavior
>
> Helm filtering of bbdb records should be lightning fast !
>
> Actual behavior from emacs-helm.sh if possible
>
> After the list of records is created, the filtering seems to "freeze" during input (typing).
>
> Buffer "helm bbdb" is updated with the list of entries names very fast.
> My bbdb database has only 50 records.

I hardly see how it would be slow with 50 candidates, I guess your
problem is your bbdb database, how did you build it ?

NOTE:
I personally don't use bbdb and I just tried right now to build a
database using gmail2bbdb-import-file and yes the database is created
but it seems not compatible with helm-bbdb.
If I create my contacts one by one using helm-bbdb all work fine.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by deusmax** [comment]
The issue is not a matter of size, since the display "freezes" at some point before or during the filtering.
You mention an incompatibility, what kind ? how is it identified ?

My bbdb database was built manually, ene record at a time using the bbdb3 interface.

**Comment by thierryvolpiatto** [comment]
deusmax <notifications@github.com> writes:

> The issue is not a matter of size, since the display "freezes" at some
> point before or during the filtering.

You confusing me, I guess what you have is errors IOW plain bug, but not
"freeze" or whatever isn't it ?

I really tried to setup a database with 131 candidates, it is really
fast to match, so far I see no issues please have a try and let me know
if something wrong.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by deusmax** [comment]
@Thierry thanks!!  Great !

 With the new version (20170505.2338) it works without the "freezing" experienced before. And it quickly searches on all bbdb fields ! 
Works ffast, as expected with helm !

**Comment by thierryvolpiatto** [comment]
deusmax <notifications@github.com> writes:

> Thierry thanks!! Great !
>
> With the new version (20170505.2338) it works without the "freezing"
> experienced before. And it quickly searches on all bbdb fields !

Glad it works fine for you, closing now.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
