### ISSUE TITLE
helm bbdb results are not identical to send-an-email

### ISSUE THREAD

**Issue by WorldsEndless** [emacs-helm/helm-bbdb#8]
## Expected behavior
When selecting names from helm-bbdb and then pressing `f4` to send email, just those names should appear, with any relevant query as to which email to address.

## Actual behavior from emacs-helm.sh if possible
If I had marked one person with the first name of "Brian" in helm-bbdb, after pressing `f4` I have an email addressing every "Brian" in my bbdb database. 

## Steps to reproduce (recipe)
With helm-bbdb, mark someone with a common name and then issue the command to email the marked recipients. 

## Backtraces if some (M-x toggle-debug-on-error)
Not applicable. Misbehaves, doesn't fail. 

## Describe versions of helm, emacs, operating system etc.
Emacs 25.3.1, helm 20170505, OpenSUSE Tumbleweed Linux.

**Comment by jagrg** [comment]
The problem is we are passing the contact's first name as a REGEXP to bbdb. For example: `(bbdb "Brian" nil)`. This is why bbdb returns all Brians in the list for you. I've sent a PR to fix this.

**Comment by WorldsEndless** [comment]
Brilliant! Thanks; I hope this goes through (is still monitored).

**Comment by jagrg** [comment]
@WorldsEndless can you please update to the latest version and confirm that this (and [this](https://github.com/emacs-helm/helm-bbdb/issues/9)) are fixed? Thanks!

**Comment by WorldsEndless** [comment]
Confirmed; thanks for the fix! This is a very welcome improvement 
that makes helm-bbdb this much more useful for me.
